# indica a Symfony que busque rutas definididas con anotaciones en los siguientes diretorios.
controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
