
#mostrar_numero:
#  path: /mostrar/numero/{numero}
#  controller: 'App\Controller\LuckyController::mostrarNumero'
#  requirements:
#    numero: '[0-9]+'

mostrar_numero_en_letras:
  path: /mostrar/numero/{letras}
  controller: 'App\Controller\LuckyController::mostrarNumeroEnLetras'
  requirements:
    numero: '[A-Za-z]+'

    